### ISSUE TITLE
HTML table numbering issue

### ISSUE THREAD

**Issue by mbtaylor** [ivoa-std/MOC#17]
The tables are numbered differently in the built PDF and HTML outputs; the last table in the PDF document is numbered 7, but the last table in the HTML document is numbered 9.  This is the case either with or without the change appled at PR #16.  The problem appears to be that TtH does not cope with the `\caption*` macro used in a couple of places in moc.tex (it was a new one on me too).

The most straightforward fix would be to replace those `\caption*` macros with `\caption`.  Another possibility, given that the affected tables don't really want to have numbers and references in the Table of Tables, would be to get rid of the `table` environments for those cases and just include the text in a simple in-line `tabular`; I think that might be a good idea anyway since this content is really inline rather than floating and table-like. Or somebody could fix TtH.

**Comment by tomdonaldson** [comment]
Solved by PR #18
